name: Github Actions Demo
on: 
  push:
    branches: 
      - main
    paths-ignore: [ .github/**]
  pull_request:
    branches: [main]
  schedule: 
    - cron: '15 6 * * 0'
  workflow_dispatch:    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "triggered by event: ${{gihub.event_name}}"
          echo "branch is ${{ github.ref}} and your repository is ."
      - uses: actions/checkout@v3
      - name: Lit files in the repo
        run: |
          echo: "the repo ${{github.repository}} contains the files:"
          tree
